### ISSUE TITLE
syntex-samples/scenario samples/Invoice Processing: SharePoint Library List Schema.xml available

### ISSUE THREAD

**Issue by schneika** [pnp/syntex-samples#21]
Dear @Spucelik for syntex-samples/scenario samples/Invoice Processing/ do you have the PnPList-Schema.xml available for the necessary SharePoint Library and List for Invoice Processing Datasource?

**Comment by Spucelik** [comment]
@schneika ... please check the solution src in this sample.  https://github.com/pnp/powerapps-samples/tree/main/samples/InvoiceProcessing.  It has a more complete sample of the source of the solution.
